=== rherardi/pst2ldif/pst2ldif.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.gssnet.com/pst2ldif"
	xmlns:tns="http://www.gssnet.com/pst2ldif" version="1.0.0.0">

	<simpleType name="sourceType">
		<restriction base="string">
			<enumeration value="PST"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="targetType">
		<restriction base="string">
			<enumeration value="LDIF"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="languageType">
		<restriction base="ID">
			<enumeration value="en"></enumeration>
			<enumeration value="fr"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="settingType">
		<restriction base="ID">
			<enumeration value="FilterRegex"></enumeration>
			<enumeration value="FilterGroup"></enumeration>
			<enumeration value="PSTFilePassword"></enumeration>
			<enumeration value="ContainerDN"></enumeration>
			<enumeration value="GroupsContainerDN"></enumeration>
			<enumeration value="MailHost"></enumeration>
			<enumeration value="Domain"></enumeration>
			<enumeration value="InputDir"></enumeration>
			<enumeration value="OutputDir"></enumeration>
			<enumeration value="LogDir"></enumeration>
			<enumeration value="LogSizeWrap"></enumeration>
			<enumeration value="MultipartBoundary"></enumeration>
			<enumeration value="SMTPAddressFile"></enumeration>
			<enumeration value="SMTPPartsSeparator"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="dateMaskType">
		<restriction base="string">
			<enumeration value="DWK, DD MMM YYYY HH:MI:SS TZHH"></enumeration>
			<enumeration value="DWK MMM DD HH:MI:SS YYYY"></enumeration>
			<enumeration value="YYYYMMDDHHMI"></enumeration>
			<enumeration value="YYYYMMDDHHMISS"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="valueModifierType">
		<restriction base="string">
			<enumeration value="uid"></enumeration>
			<enumeration value="smtpLookup"></enumeration>
		</restriction>
	</simpleType>

	<attributeGroup name="pstItemPropertyType">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="placeholder" type="string" use="required"></attribute>
		<attribute name="valueModifier" type="tns:valueModifierType"
			use="optional">
		</attribute>
		<attribute name="namedProperty" type="boolean" use="optional" default="false">
		</attribute>
	</attributeGroup>

	<complexType name="ldifEntryType">
		<sequence>
			<element name="pstItemProperty" minOccurs="0"
				maxOccurs="unbounded">
				<complexType>
					<attributeGroup ref="tns:pstItemPropertyType"></attributeGroup>
				</complexType>
			</element>
			<element name="configSetting" minOccurs="0"
				maxOccurs="unbounded">
				<complexType>
					<attributeGroup ref="tns:pstItemPropertyType"></attributeGroup>
				</complexType>
			</element>
		</sequence>
		<attribute name="attribute" type="string" use="required">
		</attribute>
		<attribute name="value" type="string" use="required">
		</attribute>
	</complexType>

	<simpleType name="filterConditionType">
		<restriction base="string">
			<enumeration value="EQUAL"></enumeration>
			<enumeration value="NOT EQUAL"></enumeration>
			<enumeration value="ONLY USERS"></enumeration>
			<enumeration value="SKIP"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="filterCombineType">
		<restriction base="string">
			<enumeration value="AND"></enumeration>
			<enumeration value="OR"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="filterBracketType">
		<restriction base="string">
			<enumeration value="("></enumeration>
			<enumeration value=")"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ldifEntryFilterType">
		<attribute name="pstItemProperty" type="string" use="required">
		</attribute>
		<attribute name="value" type="string" use="required">
		</attribute>
		<attribute name="namedProperty" type="boolean" use="optional" default="false">
		</attribute>
		<attribute name="condition" type="tns:filterConditionType" use="required">
		</attribute>
		<attribute name="combine" type="tns:filterCombineType" use="optional">
		</attribute>
		<attribute name="bracket" type="tns:filterBracketType" use="optional">
		</attribute>
	</complexType>

	<complexType name="directoryManagerType">
		<sequence>
			<element name="configEntry" minOccurs="0"
				maxOccurs="unbounded">
				<complexType>
					<attribute name="setting" type="tns:settingType"></attribute>
					<attribute name="value" type="string"
						use="required">
					</attribute>
				</complexType>
			</element>
			<element name="ldifPersonEntry" minOccurs="1">
				<complexType>
					<sequence>
						<element name="ldifEntryFilter"
							type="tns:ldifEntryFilterType" minOccurs="0" maxOccurs="unbounded">
						</element>
						<element name="ldifEntry"
							type="tns:ldifEntryType" maxOccurs="unbounded">
						</element>
					</sequence>
					<attribute name="dateFilterProperty" type="string"
						use="optional" />
					<attribute name="dateFilterAfter" type="string"
						use="optional">
					</attribute>
					<attribute name="dateFilterBefore" type="string"
						use="optional">
					</attribute>
					<attribute name="dateMask" type="tns:dateMaskType"
						use="optional" />
				</complexType>
			</element>
			<element name="ldifGroupEntry" minOccurs="1">
				<complexType>
					<sequence>
						<element name="ldifEntryFilter"
							type="tns:ldifEntryFilterType" minOccurs="0" maxOccurs="unbounded">
						</element>
						<element name="ldifEntry"
							type="tns:ldifEntryType" maxOccurs="unbounded">
						</element>
					</sequence>
					<attribute name="dateFilterProperty" type="string"
						use="optional" />
					<attribute name="dateFilterAfter" type="string"
						use="optional">
					</attribute>
					<attribute name="dateFilterBefore" type="string"
						use="optional">
					</attribute>
					<attribute name="dateMask" type="tns:dateMaskType"
						use="optional" />
				</complexType>
			</element>
		</sequence>
		<attribute name="source" type="tns:sourceType" use="required"></attribute>
		<attribute name="target" type="tns:targetType" use="required"></attribute>
	</complexType>
	<element name="directoryManager" type="tns:directoryManagerType">
	</element>
</schema>

=== rherardi/pst2ldif/pst2ldif.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:directoryManager source="PST" target="LDIF"
	xmlns:tns="http://www.gssnet.com/pst2ldif"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gssnet.com/pst2ldif pst2ldif.xsd ">

	<!-- Global configuration settings -->
	<configEntry setting="ContainerDN" value="o=ccb.com,dc=ccb,dc=com" />
	<configEntry setting="GroupsContainerDN"
		value="ou=Groups,o=ccb.com,dc=ccb,dc=com" />
	<configEntry setting="MailHost" value="hb_sun.ccb.com" />
	<configEntry setting="Domain" value="ccb.com" />
	<configEntry setting="PSTFilePassword" value="" />
	<configEntry setting="InputDir" value="" />
	<configEntry setting="OutputDir" value="c:/converted" />
	<configEntry setting="LogDir" value="" />

	<configEntry setting="SMTPAddressFile" value="pst2ldif.adr" />
	<configEntry setting="SMTPPartsSeparator" value="&lt;==&gt;" />

	<!-- Person attributes to be putted into resulted LDIF file -->
	<ldifPersonEntry>
		<ldifEntry attribute="dn"
			value="uid={uid},ou=People,{ContainerDN}">
			<pstItemProperty name="PR_SUBJECT" placeholder="{uid}" valueModifier="uid" />

			<!--
			<lotusDocField name="ShortName" placeholder="{uid}"
				multivalue="true" onlyFirstValue="true" multivalueSeparator=";" />
			<lotusDocField name="FullName" placeholder="{OrgHierarchy}"
				multivalue="true" onlyFirstValue="true" multivalueSeparator=";" orgHierarchy="true"/>
			-->
			<configSetting name="ContainerDN"
				placeholder="{ContainerDN}" />
		</ldifEntry>

		<ldifEntry attribute="changetype" value="add" />

		<ldifEntry attribute="sn" value="{sn}">
			<pstItemProperty name="PR_SURNAME" placeholder="{sn}" />

			<!--
			<lotusDocField name="LastName" placeholder="{sn}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="cn" value="{FirstName} {LastName}">
			<pstItemProperty name="PR_GIVEN_NAME" placeholder="{FirstName}" />
			<pstItemProperty name="PR_SURNAME" placeholder="{LastName}" />

			<!--
			<lotusDocField name="FirstName" placeholder="{FirstName}" />
			<lotusDocField name="LastName" placeholder="{LastName}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="iplanet-am-modifiable-by"
			value="cn=Top-level Admin Role,{ContainerDN}">
			<configSetting name="ContainerDN"
				placeholder="{ContainerDN}" />
		</ldifEntry>
		<ldifEntry attribute="givenName" value="{givenName}">
			<pstItemProperty name="PR_GIVEN_NAME" placeholder="{givenName}" />

			<!--
			<lotusDocField name="FirstName" placeholder="{givenName}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="inetUserStatus" value="Active" />
		<ldifEntry attribute="uid" value="{uid}">
			<pstItemProperty name="PR_SUBJECT" placeholder="{uid}" valueModifier="uid" />

			<!--
			<lotusDocField name="ShortName" placeholder="{uid}"
				multivalue="true" onlyFirstValue="true" multivalueSeparator=";" />
			-->
		</ldifEntry>
		<ldifEntry attribute="userPassword"
			value="{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=" />
		<ldifEntry attribute="telephonenumber"
			value="{OfficePhoneNumber}">
			<pstItemProperty name="PR_BUSINESS_TELEPHONE_NUMBER" placeholder="{OfficePhoneNumber}" />

			<!--
			<lotusDocField name="OfficePhoneNumber"
				placeholder="{OfficePhoneNumber}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="mobile" value="{CellPhoneNumber}">
			<pstItemProperty name="PR_CELLULAR_TELEPHONE_NUMBER" placeholder="{CellPhoneNumber}" />

			<!--
			<lotusDocField name="CellPhoneNumber"
				placeholder="{CellPhoneNumber}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="pager" value="{Pager}">
			<pstItemProperty name="PR_BEEPER_TELEPHONE_NUMBER" placeholder="{Pager}" />

			<!--
			<lotusDocField name="PhoneNumber_6"
				placeholder="{PhoneNumber_6}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="facsimiletelephonenumber"
			value="{OfficeFAXPhoneNumber}">
			<pstItemProperty name="PR_BUSINESS_FAX_NUMBER" placeholder="{OfficeFAXPhoneNumber}" />
 
			<!--
			<lotusDocField name="OfficeFAXPhoneNumber"
				placeholder="{OfficeFAXPhoneNumber}" />
			-->
		</ldifEntry>
		<ldifEntry attribute="l" value="{OfficeCity}, {OfficeState}">
			<pstItemProperty name="PR_BUSINESS_ADDRESS_CITY" placeholder="{OfficeCity}" />
			<pstItemProperty name="PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE" placeholder="{OfficeState}" />

			<!--
			<lotusDocField name="OfficeCity" placeholder="{OfficeCity}" />
			<lotusDocField name="OfficeState"
				placeholder="{OfficeState}" />
			-->
		</ldifEntry>

		<ldifEntry attribute="mailDeliveryOption" value="mailbox" />
		<ldifEntry attribute="mail" value="{InternetAddress}">
			<pstItemProperty name="0x8083" placeholder="{InternetAddress}" namedProperty="true" />

			<!--
			<lotusDocField name="InternetAddress" placeholder="{InternetAddress}"
				multivalue="true" onlyFirstValue="true" multivalueSeparator=";" />
			-->
		</ldifEntry>
		<ldifEntry attribute="mailHost" value="{MailHost}">
			<configSetting name="MailHost" placeholder="{MailHost}" />
		</ldifEntry>
		<ldifEntry attribute="mailUserStatus" value="active" />
		<ldifEntry attribute="mailQuota" value="-1" />
		<ldifEntry attribute="mailMsgQuota" value="-1" />

		<ldifEntry attribute="objectClass" value="userpresenceprofile" />
		<ldifEntry attribute="objectClass" value="icscalendaruser" />
		<ldifEntry attribute="objectClass"
			value="iplanet-am-user-service" />
		<ldifEntry attribute="objectClass" value="top" />
		<ldifEntry attribute="objectClass"
			value="iplanet-am-managed-person" />
		<ldifEntry attribute="objectClass" value="inetadmin" />
		<ldifEntry attribute="objectClass" value="organizationalperson" />
		<ldifEntry attribute="objectClass" value="person" />
		<ldifEntry attribute="objectClass" value="inetuser" />
		<ldifEntry attribute="objectClass"
			value="inetlocalmailrecipient" />
		<ldifEntry attribute="objectClass" value="iplanetpreferences" />
		<ldifEntry attribute="objectClass" value="ipuser" />
		<ldifEntry attribute="objectClass" value="inetorgperson" />
		<ldifEntry attribute="objectClass" value="inetsubscriber" />
		<ldifEntry attribute="objectClass" value="inetmailuser" />
		<ldifEntry attribute="objectClass" value="sunUCPreferences" />

		<ldifEntry attribute="icsStatus" value="Active" />
		<ldifEntry attribute="icsCalendar"
			value="{FirstName}@{Domain}">
			<pstItemProperty name="PR_GIVEN_NAME" placeholder="{FirstName}" />

			<!--
			<lotusDocField name="FirstName" placeholder="{FirstName}" />
			-->
			<configSetting name="Domain" placeholder="{Domain}" />
		</ldifEntry>
		<ldifEntry attribute="icsTimezone" value="America/Denver" />
		<ldifEntry attribute="icsSubscribed"
			value="{FirstName}@{Domain}${FirstName} {LastName}">
			<pstItemProperty name="PR_GIVEN_NAME" placeholder="{FirstName}" />
			<pstItemProperty name="PR_SURNAME" placeholder="{LastName}" />

			<!--
			<lotusDocField name="FirstName" placeholder="{FirstName}" />
			<lotusDocField name="LastName" placeholder="{LastName}" />
			-->
			<configSetting name="Domain" placeholder="{Domain}" />
		</ldifEntry>
		<ldifEntry attribute="icsCalendarOwned"
			value="{FirstName}@{Domain}${FirstName} {LastName}">
			<pstItemProperty name="PR_GIVEN_NAME" placeholder="{FirstName}" />
			<pstItemProperty name="PR_SURNAME" placeholder="{LastName}" />

			<!--
			<lotusDocField name="FirstName" placeholder="{FirstName}" />
			<lotusDocField name="LastName" placeholder="{LastName}" />
			-->
			<configSetting name="Domain" placeholder="{Domain}" />
		</ldifEntry>

		<ldifEntry attribute="sunUCDefaultApplication" value="mail" />
		<ldifEntry attribute="sunUCTheme" value="uwc" />
		<ldifEntry attribute="sunUCColorScheme" value="2" />
		<ldifEntry attribute="sunUCDefaultEmailHandler" value="uc" />
		<ldifEntry attribute="sunUCDateFormat" value="M/D/Y" />
		<ldifEntry attribute="sunUCDateDelimiter" value="/" />
		<ldifEntry attribute="sunUCTimeFormat" value="12" />
		<ldifEntry attribute="sunUCExtendedUserPrefs"
			value="sunUCInitialized=true" />
		<ldifEntry attribute="sunUCTimeZone" value="China/Wuhan" />

		<ldifEntry attribute="preferredLanguage" value="en" />
		<ldifEntry attribute="preferredLocale" value="en" />
	</ldifPersonEntry>

	<!-- Group attributes to be putted into resulted LDIF file -->
	<ldifGroupEntry>
		<ldifEntryFilter pstItemProperty="0x8083" value="" namedProperty="true" condition="NOT EQUAL" />

		<!--
		<ldifEntryFilter lotusDocField="InternetAddress" value="" condition="NOT EQUAL" />
		<ldifEntryFilter lotusDocField="Members" value="" condition="ONLY USERS" />
		-->

		<ldifEntry attribute="changetype" value="add" />

		<ldifEntry attribute="dn"
			value="cn={GroupName},ou=Groups,{GroupsContainerDN}">
			<pstItemProperty name="PR_SUBJECT" placeholder="{GroupName}" />

			<!--
			<lotusDocField name="ListName" placeholder="{GroupName}" extractCN="true" />
			<lotusDocField name="ListName" placeholder="{OrgHierarchy}" 
				multivalue="true" onlyFirstValue="true" multivalueSeparator=";" orgHierarchy="true"/>
			-->
			<configSetting name="GroupsContainerDN"
				placeholder="{GroupsContainerDN}" />
		</ldifEntry>
		<ldifEntry attribute="objectClass" value="top" />
		<ldifEntry attribute="objectClass" value="groupOfUniqueNames" />
		<ldifEntry attribute="cn" value="{ListName}">
			<pstItemProperty name="PR_SUBJECT" placeholder="{ListName}" />

			<!--
			<lotusDocField name="ListName" placeholder="{ListName}" extractCN="true" />
			-->
		</ldifEntry>
		<ldifEntry attribute="uniqueMember"
			value="uid={uid},{ContainerDN}">
			<pstItemProperty name="0x8054" placeholder="{uid}" namedProperty="true" valueModifier="uid"/>

			<!--
			<lotusDocField name="Members" placeholder="{uid}"
				resolveDocField="ShortName" resolveDocForm="Person" resolveDocLookupField="FullName"
				multivalue="true" multivalueSeparator=";" onlyFirstValue="false" />
			-->
			<configSetting name="ContainerDN"
				placeholder="{ContainerDN}" />
		</ldifEntry>
	</ldifGroupEntry>
</tns:directoryManager>
